name: A workflow for Hello World
on: 
  push:
    branches:
      - master
jobs:
  build: 
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: checkout repo
      - uses: ./action-a
        name: my action
        env:
          MY_NAME: "Mona"
